---
parser: babel-eslint

globals:
  __DEBUG_SERVER_ERRORS__: true
  __SERVER_ERRORS__: true

env:
  browser: true
  node: true
  mocha: true

rules:
  ### Variables
  no-undef: 2
  no-unused-vars: [2, { vars: all, args: none }]

  ### Stylistic issues
  indent: [1, 2, { SwitchCase: 1, VariableDeclarator: 1 }]
  id-length: [1, { min: 2, exceptions: [_, e, i, k, v] }]
  space-before-function-paren: [1, "never"]

