---
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Max: 99

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Style/FileName:
  # File names listed in AllCops:Include are excluded by default. Add extra
  # excludes here.
  Exclude:
    - bin/ruby-lint

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SpaceAroundEqualsInParameterDefault:
  # compatibility with RubyMine defaults (apparently can't override?)
  EnforcedStyle: space

Style/TrailingComma:
  # can't make this only apply to arrays and not params, so it's disabled
  Enabled: false
  #EnforcedStyleForMultiline: comma

Style/MultilineOperationIndentation:
  # can't convince rubymine 7 to not indent 4 spaces with mult-line expect(x).to receive ...
  Enabled: false

Style/RegexpLiteral:
  # This is required or else rubocop argues with itself when trying to escape a slash on a single-line regex
  AllowInnerSlashes: true
